#!/usr/bin/env bash
# Cross-build the six MISRC GUI dependencies for Android arm64-v8a (API 30)
# into .deps/install-android-arm64. Mirrors scripts/build-appimage-local.sh
# and the main-branch CI (build.yml) dep builds, but adds the NDK toolchain.
#
# Deps (all built static):
#   libFLAC 1.5.0   - hard-required by meson.build (flac.pc must report 1.5.0)
#   FFTW 3.3.10     - single-precision (fftw3f), required by misrc_gui
#   libsoxr 0.1.3   - optional resampler (LIBSOXR_ENABLED)
#   libusb 1.0.27   - Android backend (highest risk; FX3/DdD/hsdaoh depend on it)
#   hsdaoh          - vendored (third_party/hsdaoh); links libusb + libFLAC
#   raylib 5.5      - PLATFORM=Android, GLES 3.0, rcore_android.c
#
# Env:
#   ANDROID_NDK_HOME - NDK root (required)
#   DEPS_PREFIX      - install prefix (default: $REPO_ROOT/.deps/install-android-arm64)
#   DEPS_SRC_DIR     - source/build dir (default: $REPO_ROOT/.deps/src-android-arm64)
#   JOBS             - parallel build count (default: nproc)
#
# Idempotent: a dep is skipped if its installed .pc file already reports the
# expected version, so reruns are cheap and safe.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

: "${ANDROID_NDK_HOME:?Set ANDROID_NDK_HOME (e.g. ~/Android/Sdk/ndk/25.2.9519653)}"
DEPS_PREFIX="${DEPS_PREFIX:-$REPO_ROOT/.deps/install-android-arm64}"
DEPS_SRC_DIR="${DEPS_SRC_DIR:-$REPO_ROOT/.deps/src-android-arm64}"
JOBS="${JOBS:-$(nproc)}"

NDK="$(cd -- "$ANDROID_NDK_HOME" && pwd)"
TOOLCHAIN="$NDK/build/cmake/android.toolchain.cmake"
ABI=arm64-v8a
PLATFORM=android-30

# Sources + expected sha256 (libFLAC sha pinned from main CI build.yml).
FLAC_VERSION=1.5.0
FLAC_TARBALL="flac-${FLAC_VERSION}.tar.xz"
FLAC_URL="https://github.com/xiph/flac/releases/download/${FLAC_VERSION}/${FLAC_TARBALL}"
FLAC_SHA256="f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920"

FFTW_VERSION=3.3.10
FFTW_TARBALL="fftw-${FFTW_VERSION}.tar.gz"
FFTW_URL="https://fftw.org/${FFTW_TARBALL}"
# fftw sha verified after download (recorded, not pinned — fftw.org tarball is
# regenerated; we pin via github tag instead if the ftp sha drifts).

SOXR_VERSION=0.1.3
SOXR_TARBALL="soxr-${SOXR_VERSION}-Source.tar.xz"
SOXR_URL="https://sourceforge.net/projects/soxr/files/${SOXR_TARBALL}/download"

LIBUSB_VERSION=1.0.27
LIBUSB_TARBALL="libusb-${LIBUSB_VERSION}.tar.bz2"
LIBUSB_URL="https://github.com/libusb/libusb/releases/download/v${LIBUSB_VERSION}/${LIBUSB_TARBALL}"

RAYLIB_TAG=5.5

log() { printf '[android-deps] %s\n' "$*"; }
fail() { printf '[android-deps] ERROR: %s\n' "$*" >&2; exit 1; }

mkdir -p "$DEPS_PREFIX" "$DEPS_SRC_DIR"
export PKG_CONFIG_PATH="$DEPS_PREFIX/lib/pkgconfig:$DEPS_PREFIX/lib64/pkgconfig:${PKG_CONFIG_PATH:-}"
export CMAKE_PREFIX_PATH="$DEPS_PREFIX:${CMAKE_PREFIX_PATH:-}"

# Common CMake cross-compile flags.
cmake_x() {
  cmake "$@" \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN" \
    -DANDROID_ABI="$ABI" \
    -DANDROID_PLATFORM="$PLATFORM" \
    -DANDROID_NDK="$NDK" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_INSTALL_PREFIX="$DEPS_PREFIX" \
    -DCMAKE_FIND_ROOT_PATH="$DEPS_PREFIX"
}

# download <url> <out> [sha256]
download() {
  local url="$1" out="$2" sha="${3:-}"
  if [[ -f "$out" && -s "$out" ]]; then
    log "cached $(basename "$out")"
  else
    log "downloading $(basename "$out")"
    curl -fL --retry 3 -o "$out" "$url"
  fi
  if [[ -n "$sha" ]]; then
    local actual
    actual="$(sha256sum "$out" | awk '{print $1}')"
    [[ "$actual" == "$sha" ]] || fail "$(basename "$out") sha256 mismatch: expected $sha got $actual"
    log "sha256 ok $(basename "$out")"
  fi
}

# pc_version <name> -> echoes version or empty.
# IMPORTANT: use the cross wrapper (DEPS_PREFIX-only PKG_CONFIG_LIBDIR) so we
# only see cross-built libs, never the host x86_64 system .pc files. Otherwise
# the idempotency check falsely skips the build when the host has the same lib.
pc_version() { DEPS_PREFIX="$DEPS_PREFIX" "$SCRIPT_DIR/android-pkg-config" --modversion "$1" 2>/dev/null || true; }

VERS_FILE="$SCRIPT_DIR/deps-versions.txt"
{
  echo "# MISRC GUI Android arm64-v8a cross deps — versions + sources"
  echo "# Generated by android/build-deps-android.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# NDK: $NDK ($(grep -i Pkg.Revision "$NDK/source.properties" | awk '{print $NF}'))"
  echo "# ABI: $ABI  PLATFORM: $PLATFORM"
  echo
} > "$VERS_FILE"
record() { printf '%-18s %s\n' "$1" "$2" >> "$VERS_FILE"; }

# ---------------- libFLAC 1.5.0 ----------------
log "=== libFLAC ${FLAC_VERSION} ==="
if [[ "$(pc_version flac)" == "${FLAC_VERSION}" ]]; then
  log "skip (flac.pc already ${FLAC_VERSION})"
else
  download "$FLAC_URL" "$DEPS_SRC_DIR/$FLAC_TARBALL" "$FLAC_SHA256"
  rm -rf "$DEPS_SRC_DIR/flac-src" "$DEPS_SRC_DIR/flac-build"
  mkdir -p "$DEPS_SRC_DIR/flac-src"
  tar -xf "$DEPS_SRC_DIR/$FLAC_TARBALL" -C "$DEPS_SRC_DIR/flac-src" --strip-components=1
  cmake_x -S "$DEPS_SRC_DIR/flac-src" -B "$DEPS_SRC_DIR/flac-build" \
    -DWITH_OGG=OFF -DBUILD_TESTING=OFF -DINSTALL_MANPAGES=OFF
  cmake --build "$DEPS_SRC_DIR/flac-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/flac-build"
fi
record "libFLAC" "${FLAC_VERSION} (sha256 ${FLAC_SHA256})"

# ---------------- FFTW 3.3.10 (single precision -> fftw3f) ----------------
log "=== FFTW ${FFTW_VERSION} (fftw3f) ==="
if [[ -n "$(pc_version fftw3f)" ]]; then
  log "skip (fftw3f.pc already $(pc_version fftw3f))"
else
  download "$FFTW_URL" "$DEPS_SRC_DIR/$FFTW_TARBALL"
  FFTW_SHA="$(sha256sum "$DEPS_SRC_DIR/$FFTW_TARBALL" | awk '{print $1}')"
  rm -rf "$DEPS_SRC_DIR/fftw-src" "$DEPS_SRC_DIR/fftw-build"
  mkdir -p "$DEPS_SRC_DIR/fftw-src"
  tar -xf "$DEPS_SRC_DIR/$FFTW_TARBALL" -C "$DEPS_SRC_DIR/fftw-src" --strip-components=1
  # ENABLE_FLOAT=ON builds libfftw3f (single precision) + fftw3f.pc.
  cmake_x -S "$DEPS_SRC_DIR/fftw-src" -B "$DEPS_SRC_DIR/fftw-build" \
    -DENABLE_FLOAT=ON -DENABLE_MPI=OFF -DENABLE_OPENMP=OFF \
    -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF
  cmake --build "$DEPS_SRC_DIR/fftw-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/fftw-build"
fi
record "FFTW (fftw3f)" "${FFTW_VERSION} (sha256 ${FFTW_SHA:-$(sha256sum "$DEPS_SRC_DIR/$FFTW_TARBALL" 2>/dev/null | awk '{print $1}')})"

# ---------------- libsoxr 0.1.3 ----------------
log "=== libsoxr ${SOXR_VERSION} ==="
if [[ -n "$(pc_version soxr)" ]]; then
  log "skip (soxr.pc already $(pc_version soxr))"
else
  download "$SOXR_URL" "$DEPS_SRC_DIR/$SOXR_TARBALL"
  SOXR_SHA="$(sha256sum "$DEPS_SRC_DIR/$SOXR_TARBALL" | awk '{print $1}')"
  rm -rf "$DEPS_SRC_DIR/soxr-src" "$DEPS_SRC_DIR/soxr-build"
  mkdir -p "$DEPS_SRC_DIR/soxr-src"
  tar -xf "$DEPS_SRC_DIR/$SOXR_TARBALL" -C "$DEPS_SRC_DIR/soxr-src" --strip-components=1
  # soxr defaults to AVR (no SIMD); on aarch64 let it use NEON via WITH_SIMD.
  cmake_x -S "$DEPS_SRC_DIR/soxr-src" -B "$DEPS_SRC_DIR/soxr-build" \
    -DBUILD_TESTS=OFF -DWITH_SIMD=ON -DWITH_OPENMP=OFF
  cmake --build "$DEPS_SRC_DIR/soxr-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/soxr-build"
fi
record "libsoxr" "${SOXR_VERSION} (sha256 ${SOXR_SHA:-$(sha256sum "$DEPS_SRC_DIR/$SOXR_TARBALL" 2>/dev/null | awk '{print $1}')})"

# ---------------- libusb 1.0.27 (Android) ----------------
# HIGHEST RISK: libusb on Android. 1.0.27 ships autotools (no CMake), so we
# cross-configure with the NDK clang and --disable-udev (selects the
# linux_netlink backend; Android kernel is Linux). USB host capture on
# Android needs root or a JNI USB-Host bridge and is OUT OF SCOPE for the basic
# release — this lib only needs to LINK so hsdaoh/FX3/DdD link, with the
# connect path gated off at runtime.
log "=== libusb ${LIBUSB_VERSION} (Android backend) ==="
if [[ -n "$(pc_version libusb-1.0)" ]]; then
  log "skip (libusb-1.0.pc already $(pc_version libusb-1.0))"
else
  download "$LIBUSB_URL" "$DEPS_SRC_DIR/$LIBUSB_TARBALL"
  LIBUSB_SHA="$(sha256sum "$DEPS_SRC_DIR/$LIBUSB_TARBALL" | awk '{print $1}')"
  rm -rf "$DEPS_SRC_DIR/libusb-src"
  mkdir -p "$DEPS_SRC_DIR/libusb-src"
  tar -xf "$DEPS_SRC_DIR/$LIBUSB_TARBALL" -C "$DEPS_SRC_DIR/libusb-src" --strip-components=1
  # libusb 1.0.27 ships autotools (no CMakeLists.txt). Cross-configure with
  # the NDK clang; --disable-udev selects the linux_netlink backend (Android
  # kernel is Linux). USB capture is gated off at runtime in the basic release,
  # so this lib only needs to LINK cleanly for hsdaoh/FX3/DdD to link.
  PRE="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
  (
    cd "$DEPS_SRC_DIR/libusb-src"
    CC="$PRE/aarch64-linux-android30-clang" \
    AR="$PRE/llvm-ar" \
    RANLIB="$PRE/llvm-ranlib" \
    STRIP="$PRE/llvm-strip" \
    ./configure \
      --host=aarch64-linux-android30 \
      --prefix="$DEPS_PREFIX" \
      --disable-udev \
      --enable-static \
      --disable-shared \
      --disable-examples
    make -j "$JOBS"
    make install
  )
fi
record "libusb" "${LIBUSB_VERSION} (sha256 ${LIBUSB_SHA:-$(sha256sum "$DEPS_SRC_DIR/$LIBUSB_TARBALL" 2>/dev/null | awk '{print $1}')})"

# ---------------- libuvc (vendored from github; hsdaoh hard-requires it) ----------------
# hsdaoh CMakeLists:132 does FATAL_ERROR if libuvc is not found, so this is
# mandatory. libuvc depends on libusb (built above). Mirrors the main CI
# Windows job's libuvc build (build.yml ~510-525), adapted for the NDK.
log "=== libuvc (github main) ==="
if [[ -n "$(pc_version libuvc)" ]]; then
  log "skip (libuvc.pc already $(pc_version libuvc))"
else
  rm -rf "$DEPS_SRC_DIR/libuvc-src" "$DEPS_SRC_DIR/libuvc-build"
  git clone --depth 1 https://github.com/libuvc/libuvc.git "$DEPS_SRC_DIR/libuvc-src"
  LIBUVC_SHA="$(git -C "$DEPS_SRC_DIR/libuvc-src" rev-parse --short HEAD)"
  cmake_x -S "$DEPS_SRC_DIR/libuvc-src" -B "$DEPS_SRC_DIR/libuvc-build" \
    -DCMAKE_BUILD_TARGET=Static \
    -DBUILD_EXAMPLE=OFF \
    -DBUILD_TEST=OFF
  cmake --build "$DEPS_SRC_DIR/libuvc-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/libuvc-build"
fi
record "libuvc" "github main @ ${LIBUVC_SHA:-$(git -C "$DEPS_SRC_DIR/libuvc-src" rev-parse --short HEAD 2>/dev/null || echo unknown)}"

# ---------------- hsdaoh (vendored) ----------------
log "=== hsdaoh (vendored third_party/hsdaoh) ==="
HSDAOH_SHA="$(git -C "$REPO_ROOT/third_party/hsdaoh" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [[ -n "$(pc_version hsdaoh)" || -n "$(pc_version libhsdaoh)" ]]; then
  log "skip (hsdaoh.pc already present)"
else
  rm -rf "$DEPS_SRC_DIR/hsdaoh" "$DEPS_SRC_DIR/hsdaoh-build"
  cp -R "$REPO_ROOT/third_party/hsdaoh" "$DEPS_SRC_DIR/hsdaoh"
  # Android has no librt (clock_gettime is in libc, like macOS). hsdaoh's
  # src/CMakeLists.txt only links -lrt for hsdaoh_test on non-Apple UNIX; add
  # ANDROID to that branch so the test exe links. Patch the COPY, not the
  # vendored original (mirrors the CI Windows job's libuvc sed-patch).
  sed -i 's/if(APPLE OR CMAKE_SYSTEM MATCHES "OpenBSD")/if(APPLE OR ANDROID OR CMAKE_SYSTEM MATCHES "OpenBSD")/' \
    "$DEPS_SRC_DIR/hsdaoh/src/CMakeLists.txt"
  # Android: libusb cannot enumerate/open /dev/bus/usb/* without root, so
  # hsdaoh_open's libusb_get_device_list path fails. Patch _hsdaoh_open_uvc_device
  # to, on Android, wrap the file descriptor granted by Java UsbManager (stored
  # via android_usb_jni.c's android_usb_get_fd()) with uvc_wrap() instead of
  # uvc_find_device()+uvc_open(). uvc_wrap() uses libusb_wrap_sys_device(). We
  # create a private libusb context with LIBUSB_OPTION_NO_DEVICE_DISCOVERY and
  # hand it to uvc_init so libusb never touches /dev/bus/usb. If no fd has been
  # granted yet (permission dialog pending/declined), return LIBUSB_ERROR_ACCESS
  # so gui_capture surfaces a clear "permission" status.
  #
  # uvc_wrap is exported by libuvc.a but not in its public header, so declare it.
  HSDAOH_C="$DEPS_SRC_DIR/hsdaoh/src/libhsdaoh.c"
  python3 - "$HSDAOH_C" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
if 'android_usb_get_fd' in s:
    sys.exit(0)  # already patched (idempotent)

# (1) Declare externs + uvc_wrap prototype + Android fd-based open helper,
#     inserted just before _hsdaoh_open_uvc_device. uvc_wrap is exported by
#     libuvc.a but not in its public header, so we declare it here.
#
#     Also patch hsdaoh_get_device_count()/hsdaoh_get_device_name() to
#     short-circuit on Android: both use libusb_get_device_list (root-only on
#     Android), so they return 0/empty and the device NEVER appears in the GUI
#     dropdown — meaning the user can't select it to press connect, and the
#     permission+fd path is unreachable. On Android, report 1 device ("MS2130")
#     so it shows in the dropdown; the real VID/PID/open is deferred to the
#     permission+fd path in hsdaoh_open's android_opened branch.
decl = r'''
#if defined(__ANDROID__)
#include <libusb-1.0/libusb.h>
/* Weak fallback so hsdaoh-internal targets (hsdaoh_file/test/tcp) link
 * during the hsdaoh build. The REAL definition in android_usb_jni.c (linked
 * into libmisrc_gui.so) overrides this weak one at the GUI link, so the
 * Java-granted fd is used at runtime. */
__attribute__((weak)) int android_usb_get_fd(void) { return -1; }
extern uvc_error_t uvc_wrap(int sys_dev, uvc_context_t *context, uvc_device_handle_t **devh);
static uvc_error_t _hsdaoh_open_android_fd(hsdaoh_dev_t *dev)
{
    uvc_error_t r;
    libusb_context *usb_ctx = NULL;
    int fd = android_usb_get_fd();
    if (fd < 0)
        return UVC_ERROR_ACCESS;  /* permission not granted yet */
    if (libusb_init(&usb_ctx) != 0)
        return UVC_ERROR_IO;
    libusb_set_option(usb_ctx, LIBUSB_OPTION_NO_DEVICE_DISCOVERY);
    r = uvc_init(&dev->uvc_ctx, usb_ctx);
    if (r < 0) { libusb_exit(usb_ctx); return r; }
    r = uvc_wrap(fd, dev->uvc_ctx, &dev->uvc_devh);
    if (r < 0) { uvc_exit(dev->uvc_ctx); libusb_exit(usb_ctx); dev->uvc_ctx = NULL; }
    return r;
}
#endif
'''
marker = 'int _hsdaoh_open_uvc_device(hsdaoh_dev_t *dev)'
s = s.replace(marker, decl + '\n' + marker, 1)

# (2) Inside _hsdaoh_open_uvc_device, short-circuit to the fd path on Android.
old = 'int _hsdaoh_open_uvc_device(hsdaoh_dev_t *dev)\n{\n\tuvc_error_t r;\n\n\t/* Initialize UVC context */\n\tr = uvc_init(&dev->uvc_ctx, NULL);'
new = ('int _hsdaoh_open_uvc_device(hsdaoh_dev_t *dev)\n'
       '{\n\tuvc_error_t r;\n'
       '#if defined(__ANDROID__)\n\tr = _hsdaoh_open_android_fd(dev);\n\treturn (int)r;\n#endif\n'
       '\n\t/* Initialize UVC context */\n\tr = uvc_init(&dev->uvc_ctx, NULL);')
s = s.replace(old, new, 1)

# (3) In hsdaoh_open, skip the libusb_get_device_list enumerate on Android
#     (it fails without root, so the open is never reached). Free the
#     enumerate-only libusb ctx and jump straight to _hsdaoh_open_uvc_device,
#     then to the post-open setup (devh/claim/...). Insert an android_opened
#     label right before dev->devh = uvc_get_libusb_handle(...).
s = s.replace(
    '\tdev->dev_lost = 1;\n\n\tcnt = libusb_get_device_list(dev->ctx, &list);',
    ('\tdev->dev_lost = 1;\n'
     '#if defined(__ANDROID__)\n'
     '\t/* No /dev/bus/usb enumerate without root; use the Java-granted fd. */\n'
     '\tlibusb_exit(dev->ctx);\n'
     '\tdev->ctx = NULL;\n'
     '\tdev->vid = known_devices[0].vid;\n'
     '\tdev->pid = known_devices[0].pid;\n'
     '\tr = _hsdaoh_open_uvc_device(dev);\n'
     '\tif (r < 0) goto err;\n'
     '\tgoto android_opened;\n'
     '#endif\n\n'
     '\tcnt = libusb_get_device_list(dev->ctx, &list);'),
    1)
s = s.replace(
    '\tdev->devh = uvc_get_libusb_handle(dev->uvc_devh);',
    'android_opened:\n\tdev->devh = uvc_get_libusb_handle(dev->uvc_devh);',
    1)

# (4) Patch hsdaoh_get_device_count() and hsdaoh_get_device_name() on Android
#     to short-circuit the root-only libusb_get_device_list path: report 1
#     device (the first known_devices entry, e.g. "MS2130") so it appears in
#     the GUI dropdown without root. Insert the android short-circuit right
#     after each function's opening brace.
s = s.replace(
    'uint32_t hsdaoh_get_device_count(void)\n{\n\tint i,r;\n\tlibusb_context *ctx;\n\tlibusb_device **list;\n\tuint32_t device_count = 0;\n\tstruct libusb_device_descriptor dd;\n\tssize_t cnt;\n',
    ('uint32_t hsdaoh_get_device_count(void)\n{\n'
     '#if defined(__ANDROID__)\n'
     '\t/* No rootless libusb enumerate on Android; report 1 known device so it\n'
     '\t * shows in the GUI dropdown. Real open is deferred to the fd path. */\n'
     '\treturn 1;\n'
     '#endif\n'
     '\tint i,r;\n\tlibusb_context *ctx;\n\tlibusb_device **list;\n\tuint32_t device_count = 0;\n\tstruct libusb_device_descriptor dd;\n\tssize_t cnt;\n'),
    1)
s = s.replace(
    'const char *hsdaoh_get_device_name(uint32_t index)\n{\n\tint i,r;\n\tlibusb_context *ctx;\n\tlibusb_device **list;\n\tstruct libusb_device_descriptor dd;\n\thsdaoh_adapter_t *device = NULL;\n\tuint32_t device_count = 0;\n\tssize_t cnt;\n',
    ('const char *hsdaoh_get_device_name(uint32_t index)\n{\n'
     '#if defined(__ANDROID__)\n'
     '\t/* No rootless libusb enumerate on Android; return the first known\n'
     '\t * device name so the dropdown shows something meaningful. */\n'
     '\t(void)index;\n'
     '\treturn known_devices[0].name;\n'
     '#endif\n'
     '\tint i,r;\n\tlibusb_context *ctx;\n\tlibusb_device **list;\n\tstruct libusb_device_descriptor dd;\n\thsdaoh_adapter_t *device = NULL;\n\tuint32_t device_count = 0;\n\tssize_t cnt;\n'),
    1)

open(p, 'w').write(s)
PY
  log "patched hsdaoh_open + _hsdaoh_open_uvc_device + get_device_count/name for Android fd-based uvc_wrap"
  # hsdaoh uses pkg_check_modules(flac) + libusb; DEPS_PREFIX is on
  # PKG_CONFIG_PATH/CMAKE_FIND_ROOT_PATH so the cross flac/libusb resolve.
  # CFLAGS -I adds the vendored FLAC include dir for hsdaoh_file (mirrors CI).
  export CFLAGS="-I${DEPS_PREFIX}/include ${CFLAGS:-}"
  export CXXFLAGS="-I${DEPS_PREFIX}/include ${CXXFLAGS:-}"
  cmake_x -S "$DEPS_SRC_DIR/hsdaoh" -B "$DEPS_SRC_DIR/hsdaoh-build" \
    -DINSTALL_UDEV_RULES=OFF
  cmake --build "$DEPS_SRC_DIR/hsdaoh-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/hsdaoh-build"
  for PCDIR in "$DEPS_PREFIX/lib/pkgconfig" "$DEPS_PREFIX/lib64/pkgconfig"; do
    if [[ -f "$PCDIR/libhsdaoh.pc" && ! -f "$PCDIR/hsdaoh.pc" ]]; then
      cp "$PCDIR/libhsdaoh.pc" "$PCDIR/hsdaoh.pc"
    fi
  done
fi
record "hsdaoh" "vendored @ ${HSDAOH_SHA}"

# ---------------- raylib 5.5 (PLATFORM=Android, GLES 3.0) ----------------
log "=== raylib ${RAYLIB_TAG} (PLATFORM=Android) ==="
RAYLIB_SHA="$(git -C "$REPO_ROOT/.deps/src-appimage-local/raylib" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [[ -n "$(pc_version raylib)" ]]; then
  log "skip (raylib.pc already $(pc_version raylib))"
else
  # Reuse the raylib checkout the native build already cloned (5.5 tag).
  RAYLIB_SRC="$REPO_ROOT/.deps/src-appimage-local/raylib"
  if [[ ! -d "$RAYLIB_SRC/.git" ]]; then
    rm -rf "$RAYLIB_SRC"
    git clone --depth 1 --branch "$RAYLIB_TAG" https://github.com/raysan5/raylib.git "$RAYLIB_SRC"
  fi
  rm -rf "$DEPS_SRC_DIR/raylib-build"
  # raylib 5.5 bug: rlgl.h:1908-1909 has inverted ES3/non-ES3 branches in
  # rlActiveDrawBuffers(). Under GRAPHICS_API_OPENGL_ES3 it calls
  # glDrawBuffersEXT (an ES2 extension symbol ABSENT on GLES3) instead of
  # glDrawBuffers (the GLES3 core function). This causes an undefined-symbol
  # link error. Fix: use glDrawBuffers on the ES3 path. Only occurrence in rlgl.h.
  sed -i 's/glDrawBuffersEXT(count, buffers);/glDrawBuffers(count, buffers);/' \
    "$RAYLIB_SRC/src/rlgl.h"
  # raylib LibraryConfigurations.cmake: PLATFORM=Android -> PLATFORM_ANDROID,
  #   compiles android_native_app_glue.c from $ANDROID_NDK, links
  #   m log android EGL GLESv2 OpenSLES atomic c. We override GRAPHICS to ES 3.0
  #   so the GUI visualizers get GLES3 (rlgl uses ES3 paths).
  cmake -S "$RAYLIB_SRC" -B "$DEPS_SRC_DIR/raylib-build" \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN" \
    -DANDROID_ABI="$ABI" \
    -DANDROID_PLATFORM="$PLATFORM" \
    -DANDROID_NDK="$NDK" \
    -DPLATFORM=Android \
    -DOPENGL_VERSION="ES 3.0" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_GAMES=OFF \
    -DCMAKE_INSTALL_PREFIX="$DEPS_PREFIX" \
    -DCMAKE_FIND_ROOT_PATH="$DEPS_PREFIX"
  cmake --build "$DEPS_SRC_DIR/raylib-build" --parallel "$JOBS"
  cmake --install "$DEPS_SRC_DIR/raylib-build"
fi
record "raylib" "${RAYLIB_TAG} @ ${RAYLIB_SHA}"

# ---------------- fix cross raylib.pc for Android ----------------
# raylib's CMake install emits a Desktop-style raylib.pc: `Requires.private:
# glfw3` and empty `Libs.private`. That is WRONG for the PLATFORM=Android
# build (rcore_android.c uses EGL/ANativeWindow, not glfw). With our cross
# pkg-config wrapper forcing --static, the bogus glfw3 require makes
# `pkg-config --static --cflags/libs raylib` fail, and Meson then falls back to
# CMake and picks up a HOST x86_64 /usr/local/lib/libraylib.a (arch mismatch).
# Fix: drop the glfw3 require and record the real Android platform libs the
# static libraylib.a needs. Run unconditionally so reruns stay correct.
RAYLIB_PC="$DEPS_PREFIX/lib/pkgconfig/raylib.pc"
if [[ -f "$RAYLIB_PC" ]]; then
  sed -i '/^Requires.private: glfw3/d' "$RAYLIB_PC"
  # If Libs.private is empty, fill in the rcore_android.c platform deps.
  if grep -q '^Libs.private: *$' "$RAYLIB_PC"; then
    sed -i 's|^Libs.private: *$|Libs.private: -lm -llog -landroid -lEGL -lGLESv2 -lOpenSLES -latomic|' "$RAYLIB_PC"
  fi
  log "patched raylib.pc (removed glfw3 require; set Android Libs.private)"
fi

# ---------------- summary ----------------
log "=== installed .pc versions ==="
for pc in flac fftw3f soxr libusb-1.0 libuvc hsdaoh libhsdaoh raylib; do
  v="$(pc_version "$pc")"
  printf '  %-14s %s\n' "$pc" "${v:-(missing)}"
done
log "wrote $VERS_FILE"
log "deps cross-build complete."
