#!/usr/bin/env bash
# Generate a Meson cross-file for Android arm64-v8a (API 30).
#
# Inputs (env):
#   ANDROID_NDK_HOME  - NDK root (e.g. ~/Android/Sdk/ndk/25.2.9519653)
#   DEPS_PREFIX       - install prefix for cross-built deps (e.g. .deps/install-android-arm64)
#
# Output:
#   android/aarch64-linux-android.ini  (overwritten)
#
# The cross-file points Meson at the NDK LLVM clang (API-30 suffixed so the
# default API level is 30), llvm-ar/strip/nm/ranlib, the NDK sysroot, and a
# cross pkg-config wrapper (android/android-pkg-config) that restricts
# PKG_CONFIG_LIBDIR to DEPS_PREFIX so Meson cannot pick up host .pc files.
#
# Why a generator instead of a static .ini: NDK + deps paths differ between
# dev hosts and CI, and Meson cross-files do not expand env vars. Mirrors the
# dynamic config approach used by scripts/build-appimage-local.sh.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

: "${ANDROID_NDK_HOME:?Set ANDROID_NDK_HOME to the NDK root (e.g. ~/Android/Sdk/ndk/25.2.9519653)}"
: "${DEPS_PREFIX:?Set DEPS_PREFIX to the cross deps install prefix (e.g. $REPO_ROOT/.deps/install-android-arm64)}"

NDK="$(cd -- "$ANDROID_NDK_HOME" && pwd)"
PRE="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
SYSROOT="$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
DEPS_PREFIX="$(cd -- "$DEPS_PREFIX" && pwd)"
WRAPPER="$SCRIPT_DIR/android-pkg-config"

# Validate the toolchain exists.
[[ -x "$PRE/aarch64-linux-android30-clang" ]] || { echo "ERROR: $PRE/aarch64-linux-android30-clang not found" >&2; exit 1; }
[[ -x "$WRAPPER" ]] || { echo "ERROR: $WRAPPER not found (run from repo, chmod +x it)" >&2; exit 1; }

OUT="$SCRIPT_DIR/aarch64-linux-android.ini"

cat > "$OUT" <<EOF
# Auto-generated by android/gen-cross-file.sh — do not edit by hand.
# Target: aarch64-linux-android, API level 30 (Android 11+).
# Regenerate after moving the NDK or DEPS_PREFIX.

[binaries]
c = '$PRE/aarch64-linux-android30-clang'
cpp = '$PRE/aarch64-linux-android30-clang++'
ar = '$PRE/llvm-ar'
as = '$PRE/llvm-as'
ld = '$PRE/ld.lld'
strip = '$PRE/llvm-strip'
nm = '$PRE/llvm-nm'
ranlib = '$PRE/llvm-ranlib'
objcopy = '$PRE/llvm-objcopy'
pkg-config = '$WRAPPER'
; The NDK ships its own CMake toolchain; expose it for any cmake subproject.
cmake = '$(command -v cmake)'

[built-in options]
; NOTE: -D__ANDROID_API__=30 is NOT set here — the API-30-suffixed clang
; (aarch64-linux-android30-clang) defines __ANDROID_API__=30 itself, and
; redefining it triggers -Wmacro-redefined (fatal under -Werror). -DANDROID is
; kept because the NDK does not define it for the clang driver.
c_args = ['-DANDROID', '-fPIC', '-pthread', '-funwind-tables', '--sysroot=$SYSROOT', '-I$SYSROOT/usr/include', '-I$SYSROOT/usr/include/aarch64-linux-android']
cpp_args = ['-DANDROID', '-fPIC', '-pthread', '-funwind-tables', '--sysroot=$SYSROOT', '-I$SYSROOT/usr/include', '-I$SYSROOT/usr/include/aarch64-linux-android']
; lib paths so Meson link checks find the cross sysroot + vendored deps
c_link_args = ['-L$SYSROOT/usr/lib/aarch64-linux-android/30', '-L$DEPS_PREFIX/lib', '-L$DEPS_PREFIX/lib64', '--sysroot=$SYSROOT', '-Wl,--exclude-libs,libatomic.a', '-Wl,-z,noexecstack', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,--build-id', '-u', 'ANativeActivity_onCreate']
cpp_link_args = ['-L$SYSROOT/usr/lib/aarch64-linux-android/30', '-L$DEPS_PREFIX/lib', '-L$DEPS_PREFIX/lib64', '--sysroot=$SYSROOT', '-Wl,--exclude-libs,libatomic.a', '-Wl,-z,noexecstack', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,--build-id', '-u', 'ANativeActivity_onCreate']

[properties]
sys_root = '$SYSROOT'
; We cannot run arm64 binaries on the x86_64 host (no emulator at configure
; time), but misrc_tools/meson.build does not use cc.run(), so no exe wrapper
; is needed. Compile/link checks (cc.has_function/has_header/sizeof) work
; against the NDK sysroot without execution.
needs_exe_wrapper = false
; Let Meson's pkg-config know where vendored cross .pc files live.
pkg_config_path = '$DEPS_PREFIX/lib/pkgconfig:$DEPS_PREFIX/lib64/pkgconfig'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
EOF

echo "Wrote $OUT"
echo "--- summary ---"
grep -E "^(c |cpp |ar |strip |nm |pkg-config|system |cpu_family |sys_root |needs_exe_wrapper)" "$OUT"
